### ISSUE TITLE
Example callback will leak user session to client

### ISSUE THREAD

**Issue by ngbrown** [sergiodxa/remix-auth#143]
### Describe the bug

The use of returning the result of `authenticator.authenticate` in the examples allows the client to re-submit the request once logged in and get a json response of the user session. Usually this content is protected by storage or encrypted cookies.

https://github.com/sergiodxa/remix-auth/blob/main/README.md?plain=1#L124-L132

This applies to the examples in the `remix-auth-oauth2` repo even more since it's probable for access tokens to be stored in the user session.

A better approach would be simply await it and then throw an error:

```ts
  await authenticator.authenticate("user-pass", request, {
    successRedirect: "/dashboard",
    failureRedirect: "/login",
  });

  throw new Error("already logged in");
```

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

I expect the examples to show a more secure path.

### Platform

N/A

**Comment by sergiodxa** [comment]
In this snippet:

```ts
await authenticator.authenticate("user-pass", request, {
  successRedirect: "/dashboard",
  failureRedirect: "/login",
});

throw new Error("already logged in");
```

The error will never happen, because you defined both successRedirect and failureRedirect, so if the user is authenticated a redirect to `/dashboard` will be thrown, if the user is not authenticated then it will redirect to `/login`. There's no scenario where the data of the session is returned directly if you set both redirects.

If you don't set the failureRedirect then it will redirect if it's logged-in or return null if it's not.

If you don't set the successRedirect then it will redirect if it's not logged-in and return the user (whatever the strategies return) data if it is.

In the last scenario is when it can leak the data, but that's the responsibility of the dev using the library, the type will be correctly defined to tell you that it's returning the user data.

All of this is documented in the README

<img width="866" alt="Screen Shot 2022-03-14 at 16 11 10" src="https://user-images.githubusercontent.com/1312018/158261973-eb9d2cdc-1d69-4be4-a69b-bba7436dde73.png">

**Comment by ngbrown** [comment]
I opened the issue because it happened to me when I had an error display and I re-loaded the page. The raw json from the session was displayed in the browser.

Another way besides a reload would be to look through the network logs in the browser and re-submit the request from within a logged in user session.
